### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by zieone** [GordStephen/pdsite#5]
What license is this code under?

I want to make it work on the BSD's via standard POSIX shell, instead of the unsafe bash that it is now.

**Comment by GordStephen** [comment]
First, let me say it would be great to have this properly POSIX compliant!

Good question about the license, I'll make it BSD three-clause.

**Comment by zieone** [comment]
Awesome.  Without a license, I didn't want to make any changes to the code, as I didn't want to break any laws.  Next time I get around to messing with my websites again I'll play with making this POSIX compliant.

May I ask why you picked YAML for config, when a simple shell sourced script with variables would have been way easier and less error-prone(since you don't need all those lines to drag config out of a YAML file..)

The config stuff as is doesn't work properly under BSD, since sed behaves differently and you get ' default' instead of 'default' (i.e. a space at the beginning). that's what got me upset with this code ;)
